### ISSUE TITLE
zabbix_sender [8]: ERROR: [line 8] 'Key value' required

### ISSUE THREAD

**Issue by Rascree** [pthoelken/fritzbox-zabbix-monitoring#10]
Hi!
I created the container on portainer for a qnap container station. I encountered the issue "zabbix_sender [8]: ERROR: [line 1] 'Hostname' required" which was already known. Since I used portainer to create the container end entered the ENV variables manuell, i have no idea where the compose.yml is stored. So i tried a different way to use a stack and directly copy&paste the content of the yml into the stack.
That seemed to work fine, but not i got the issue

zabbix_sender [8]: ERROR: [line 8] 'Key value' required

I'm not even sure what line 8 is, or what kind of key is requried. Maybe you have an idea.

Many thanks!

**Comment by pthoelken** [comment]
Thanks for your report @Rascree - as I understand you correctly in a Portainer Environment it's doesn't run (your error comes up) and if you running these on your docker host like "docker-compose up" with your docker-compose.yml file it works well? 

I need this informations to try to reproduce your case.

**Comment by Rascree** [comment]
Hallo,

 

wir können vermutlich auch auf deutsch schreiben….

 

Ich habe das bisher nicht über den host direkt gestartet. Ich habe erst nicht verstanden, wo genau das .yml fiel überhaupt liegt, und habe online gesehen, dass beim beim Einrichten von Stacks die .yml Einstellungen einfach rein kopieren kann.

 

Was ich der Reihe nach gemacht habe

*	QNAP Container Station läuft auf meinem NAS inkl. Portainer. Darauf läuft alles mögliche von grafane, influx, openhab bis pihole
*	Ziel: Das Heim-Netzwerk monitoren von simplen PINGs bis Netwerksdurchsatz und was über SNMP sonst noch rein kommt
*	Dann: Zabbix Server und mySQL über portainer installiert. Einfach übers Web-Inferface, Add container und die ENV variabeln einzeln eingetragen
*	Port mappings kontrolliert, datenbanken etcpp eingerichtet. Funktioniert soweit. Ich kann den router leider nur pingen, und die switche über SNMP v2 verbinden. 
*	Ich habe 3 Fritzboxen als WLAN Access points im Haus verteilt, und festgestellt, dass zabbix da nicht einfach dran kann, und fritz.box kein SNMP hat
*	Also fritzbox-zabbix-monitorin als container wieder über portainer installiert. Manuell über portainer. Add container, dann die ENV variablen wie online angegeben. 

*	FRITZBOX_HOSTNAME: fritz-box
*	FRITZBOX_IP: 192.168.11.XXX
*	FRITZBOX_USER: zabbixmonitor
*	FRITZBOX_PASSWD: ****
*	INTERVAL: 30s
*	ZABBIX_SERVER: 192.168.11.XXX
*	Dann habe ich den User auf der Fritzbox mit Username und PWD eingerichtet.

*	Erfolg war der Fehler, der auf github beschrieben war. Lösung sollte sein, dass die „ in der .yml weg müssen. Da ich die .yml nicht direkt verwendet hatte, und keine „ eingetragen hatte, konnte ich den Fehler so nicht beheben.
*	Ich wollte dann den container nochmal neu über die Konsole bauen und habe im QNAP nach den entsprechenden verzeichnissen und .yml files gesucht. Das war erfolglos, daher war mit nicht klar, wie ich überhaupt ein „docker-compose up“ durchführen sollte.
*	Ich habe dann online gesehen, dass mann über einen „stack“ im portainer ein .yml file importieren kann, bzw auch direkt in der webseite den code eintragen kann. Das habe ich dann gemacht
*	Also stack erstellt. Den Inhalt des .yml files direkt in die webmakse kopiert, dann die variablen entsprechend angepasst und den stack installiert.

 

 

Ergebnis ist am Ende der neue Fehler wie angegeben. Hier noch ein Screeshot der ENV wie er im Portainer derzeit angezeigt wird, und ein Screenshot des Logiles.

 



 





 

Ich weiß leider nicht wo ich genau nach line 8 suchen soll. Mir fehlt noch das file dazu. 

 

Danke und viele Grüße,

Rascree

 

 

Von: Patrick Thoelken ***@***.***> 
Gesendet: Sonntag, 29. Oktober 2023 11:28
An: pthoelken/fritzbox-zabbix-monitoring ***@***.***>
Cc: Rascree ***@***.***>; Mention ***@***.***>
Betreff: Re: [pthoelken/fritzbox-zabbix-monitoring] zabbix_sender [8]: ERROR: [line 8] 'Key value' required (Issue #10)

 

Thanks for your report @Rascree <https://github.com/Rascree>  - as I understand you correctly in a Portainer Environment it's doesn't run (your error comes up) and if you running these on your docker host like "docker-compose up" with your docker-compose.yml file it works well?

I need this informations to try to reproduce your case.

**Comment by pthoelken** [comment]
Deine Screenshots kann ich leider nicht sehen, da du vermutlich über eine E-Mail geantwortet hast. 

Zu dem Problem, ich werde nächste Woche einmal versuchen das nachzustellen und dann schauen. Der Fehler selbst sagt vermutlich nur aus, dass ihm Variablen fehlen, bzw. die durch Portainer nicht sauber übergeben werden. 

Ich schaue mir das kommende Woche an und melde mich dann direkt nochmal bei dir.

**Comment by pthoelken** [comment]
Also ich erhalte keine Probleme, wenn ich folgendes mache:

1. Öffne Portainer und wähle meine Dockerumgebung
2. App Template > Custom Template
3. Create Custom Template
4. Webeditor > paste my docker-compose.yml file into it (from below for example)
5. Create Template
6. App Template > Custom Template > Choose my created template
7. Deploy Stack
8. Stacks > go to my deploed stack and check if the container is up and running

So in my caste after "deploy Stack" the container was up and running corrctly. 

This was the docker-compose.yml which I use for: 
```
version: '3.2'
services:
  fritzbox-zabbix-monitoring:
    image: pthoelken/fritzbox-zabbix-monitoring:latest
    restart: always
    environment:
      - ZABBIX_SERVER=192.168.178.X
      - FRITZBOX_HOSTNAME=fritz.box
      - FRITZBOX_IP=192.168.178.X
      - INTERVAL=30s
      - FRITZBOX_USER=zabbixmonitor
      - FRITZBOX_PASSWD=asoc8nwN9C%hNr71tLfBfPJo5ciN8
```
What I see in your case is your hostname looks akward ... FRITZBOX_HOSTNAME must be the same in docker-compose as the same from Zabbix. The visiable name doesn't matter, but the hostname from zabbix host and from enviroment variables must be the same. 

![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/12643853/feaca4d5-719e-41ce-804d-8296c1f3bbc7)

![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/12643853/565482f9-f0df-4ad3-a2b3-c07194772e87)

**Comment by Rascree** [comment]
Na, zumindest läßt sich das überall gleich nachstellen.

 

Ich habe dasselbe Ergebnis bekommen, wie bisher. Ich habe allerdings bisher nur versucht den fritzbox-zabbix-monitoring container zu starten. Ich habe auf der Zabbix Seite noch nicht weiter gemacht.

 

Das hab ich jetzt ergänzt. Das Template läßt ich nicht laden „Invalid tag „/zabbix_export/version“: unsuported version number.“

 

Ich habe dann den Host erstmal ohne template angelegt.

*	Hostname fritz.box, also identisch zum template
*	Templetes jetzt leer
*	Host groups habe ich eine neue für Access Points gemacht
*	Interface war mir nicht klar. Habe einen „Agent“ mit der IP des fritzbox-zabbix-monitoring containers auf Port 10051 erstellt.

 

 

Der zabbix_sender hat noch denselben fehler, und der zabbix host verbindet sich leider nicht.

 

 

 

 

Von: Patrick Thoelken ***@***.***> 
Gesendet: Sonntag, 29. Oktober 2023 13:10
An: pthoelken/fritzbox-zabbix-monitoring ***@***.***>
Cc: Rascree ***@***.***>; Mention ***@***.***>
Betreff: Re: [pthoelken/fritzbox-zabbix-monitoring] zabbix_sender [8]: ERROR: [line 8] 'Key value' required (Issue #10)

 

Also ich erhalte keine Probleme, wenn ich folgendes mache:

1.	Öffne Portainer und wähle meine Dockerumgebung
2.	App Template > Custom Template
3.	Create Custom Template
4.	Webeditor > paste my docker-compose.yml file into it (from below for example)
5.	Create Template
6.	App Template > Custom Template > Choose my created template
7.	Deploy Stack
8.	Stacks > go to my deploed stack and check if the container is up and running

So in my caste after "deploy Stack" the container was up and running corrctly.

This was the docker-compose.yml which I use for:

version: '3.2'
services:
  fritzbox-zabbix-monitoring:
    image: pthoelken/fritzbox-zabbix-monitoring:latest
    restart: always
    environment:
      - ZABBIX_SERVER=192.168.178.X
      - FRITZBOX_HOSTNAME=fritz.box
      - FRITZBOX_IP=192.168.178.X
      - INTERVAL=30s
      - FRITZBOX_USER=zabbixmonitor
      - FRITZBOX_PASSWD=asoc8nwN9C%hNr71tLfBfPJo5ciN8

What I see in your case is your hostname looks akward ... FRITZBOX_HOSTNAME must be the same in docker-compose as the same from Zabbix. The visiable name doesn't matter, but the hostname from zabbix host and from enviroment variables must be the same.

 <https://user-images.githubusercontent.com/12643853/278869430-feaca4d5-719e-41ce-804d-8296c1f3bbc7.png> 

 <https://user-images.githubusercontent.com/12643853/278869466-565482f9-f0df-4ad3-a2b3-c07194772e87.png>

**Comment by pthoelken** [comment]
Du musst erst auf der Zabbix Monitoring Seite den Host erstellen, welche so aussehen muss: 

![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/12643853/936de24e-5801-4c44-9b41-6c0672a8eb34)

Es wird kein Interface benötigt, da hier mit einem Zabbix Sender im Container gearbeitet wird. 

Dann erst den Container starten.

https://github.com/pthoelken/fritzbox-zabbix-monitoring/blob/main/templates/template_avm_fritzbox.xml  - das Template funktioniert auf jeden Fall mit der Zabbix Version 7.

**Comment by Rascree** [comment]
Okay, danke für die Info.

 

*	Ich habe nur Version 6.4 von Zabbix, die war als „latest“ gekennzeichnet. Vermutlich liegts daran, dass das template nicht importiert werden konnte.
*	Ich habe dann zabbix auf 7.0 alpha upgegradet. Das passte danach nicht mehr zur MySQL. Dann habe ich die auf 8.2 geupdated. Dann kam der zabbix server damit nicht mehr zurecht, und meinte er bräuchte 8.1, also mysql runter geschmissen, und wieder neu als 8.1 installiert
*	Dann zabbix als 7.0er neu drauf
*	Jetzt meckert der zabbix web nginx, dass die database version nicht zu den aktuellen requirements passen…

 

Langer rede kurzer Sinn.. ich muss die Woche nochmal basteln und melde mich dann, wenn ich das template mit den entsprechenden Einstellungen verwenden kann. Ich habe aber verstanden, wie es funktionieren sollte. Merci.

 

 

 

 

Von: Patrick Thoelken ***@***.***> 
Gesendet: Sonntag, 29. Oktober 2023 15:47
An: pthoelken/fritzbox-zabbix-monitoring ***@***.***>
Cc: Rascree ***@***.***>; Mention ***@***.***>
Betreff: Re: [pthoelken/fritzbox-zabbix-monitoring] zabbix_sender [8]: ERROR: [line 8] 'Key value' required (Issue #10)

 

Du musst erst auf der Zabbix Monitoring Seite den Host erstellen, welche so aussehen muss:

 <https://user-images.githubusercontent.com/12643853/278878024-936de24e-5801-4c44-9b41-6c0672a8eb34.png> 

Es wird kein Interface benötigt, da hier mit einem Zabbix Sender im Container gearbeitet wird.

Dann erst den Container starten.

https://github.com/pthoelken/fritzbox-zabbix-monitoring/blob/main/templates/template_avm_fritzbox.xml - das Template funktioniert auf jeden Fall mit der Zabbix Version 7.

**Comment by pthoelken** [comment]
Ja, das stimmt wohl. Ich arbeite derzeit mit den neuesten Alpha Versionen, da ich auch Module in Zabbix selbst entwickle. Daher verwende ich oftmals eine andere Version. 

Aber das hochziehen auf eine neuere Zabbix Version ist nicht all zu tragisch. Viel verrät dir das Log, wenn Dienste nicht starten. Ich habe auch oftmals das Problem nach einem Update, dass ich den Service (systemctl restart zabbix-server etc...) zwei mal nach einander neustarten muss (ebenso die Datenbank) und anschließend hat sich alles gefangen. Gerade auch bei den Anzeigen, dass die Versionen nicht zueinander passen. 

Aber probiere dich gerne aus und melde dich wieder, wenn es Schwierigkeiten gibt. Ich kann sonst die Tage auch gerne einmal ein Video von dem ganzen machen, wenn ich es zeitlich schaffe.

**Comment by Rascree** [comment]
Servus,

 

Ich habe inzwischen alles auf dem neuesten Stand.

*	mySQL läuft auf Version 8.1 dem QNAP docker im 10.0.0.0er subnetz mit der port 3306 auf dem QNAP 192.168.11.60 publiziert. Klappt
*	Zabbix Server läuft auf QNAP docker in der 7.0er alpha und ist direkt im LAN auf 192.168.11.177

*	DB_SERVER_HOST ist 192.168.11.60
*	DB_SERVER_PORT ist 3306
*	DB user, pwd, root pwd sind eingetragen

*	Zabbix-web-nginx läuft im QNAP docker und ist auch in der -trunk version installiert, die zum server passt. Läuft auch im LAN unter 192.168.11.76

*	DB_SERVER etcpp definiert wie oben
*	ZBX_SERVER_HOST ist 192.168.11.177

*	pthoelken/fritzbox-zabbix-monitoring:latest läuft im QNAP docker auch übers LAN auf 192.168.11.203

*	FRITZBOX_HOSTNAME = fritz.box
*	FRITZBOX_IP = 192.168.11.46
*	FRITZBOX_PASSWD und USER = entsprechend zabbixmonitor/*** und auf der Fritzbox neuen user eingerichtet
*	INTERVAL = 30s
*	ZABBIX_SERVER = 192.168.11.177

 

Im Zabbix Web Nginx folgendes durchgeführt

*	Template aus dem link runtergeladen und installiert. Hier gab es einen Konflikt mit der bestehenden template group, die er irgendwie nicht aktualisieren wollte. Habe die alte in tamplate group_old umbenannt, danach ging der import
*	Host name ist fritz.box
*	Visible Name ist Fritz Box 4060
*	Template ist Template AVM FritzBox Router
*	Host group ist Linux server
*	Kein Interface etcpp eingetragen. Rest leer

 

 

Im Portainer sehe ich, dass die container alle laufen. 

 

Logile fritzbox_zabbix_monitoring

                    zabbix_sender [194]: ERROR: [line 8] 'Key value' required

         Sending failed.

 

Sonst laufen die logiles durch, ohne das Probleme auftreten.

 

*	Daten aus der Fritzbox kommen noch nicht im zabbix an. „fritz.box: No Values incoming for uptime“

 

Ich habe 3 Fritzboxen laufen. Alle laufen als Access Point, d.h. keine übernimmt Routerfunktionen. Daher ist auch die übliche Einrichtung über „fritz.box“ als host nicht drin. Ich gehe über die verschiedenen IPs. Der Router ist ein ASUS Router.

 

Wie könnte ich noch testen und den Fehler eingrenzen?

 

Viele Grüße!

 

 

 

 

 

Von: Patrick Thoelken ***@***.***> 
Gesendet: Sonntag, 29. Oktober 2023 17:56
An: pthoelken/fritzbox-zabbix-monitoring ***@***.***>
Cc: Rascree ***@***.***>; Mention ***@***.***>
Betreff: Re: [pthoelken/fritzbox-zabbix-monitoring] zabbix_sender [8]: ERROR: [line 8] 'Key value' required (Issue #10)

 

Ja, das stimmt wohl. Ich arbeite derzeit mit den neuesten Alpha Versionen, da ich auch Module in Zabbix selbst entwickle. Daher verwende ich oftmals eine andere Version.

Aber das hochziehen auf eine neuere Zabbix Version ist nicht all zu tragisch. Viel verrät dir das Log, wenn Dienste nicht starten. Ich habe auch oftmals das Problem nach einem Update, dass ich den Service (systemctl restart zabbix-server etc...) zwei mal nach einander neustarten muss (ebenso die Datenbank) und anschließend hat sich alles gefangen. Gerade auch bei den Anzeigen, dass die Versionen nicht zueinander passen.

Aber probiere dich gerne aus und melde dich wieder, wenn es Schwierigkeiten gibt. Ich kann sonst die Tage auch gerne einmal ein Video von dem ganzen machen, wenn ich es zeitlich schaffe.

**Comment by pthoelken** [comment]
Danke für deine Rückmeldung. Gehe mal bitte in die CLI deines laufenden Containers und führe das folgende aus: 

`php status.php`

und poste das Ergebnis. Sensible Daten wie IP Adresse bitte verfälschen / schwärzen.

**Comment by Rascree** [comment]
/app # ls

send        status.php

/app # php status.php

fritz.box totalBytesSent 0

fritz.box totalBytesReceived 0

fritz.box layer1UpstreamMaxBitRate 0

fritz.box layer1DownstreamMaxBitRate 0

fritz.box physicalLinkStatus Up

fritz.box connectionStatus Unconfigured

fritz.box uptime 0

fritz.box externalIPAddress

fritz.box softwareVersion 261.07.57

fritz.box associatedDeviceDiscovery {"data":[{"{#MAC}":"00:80:92:CD:F8:8B"},{"{#MAC}":"7E:C0:EE:63:1A:1C"},{"{#MAC}":"68:A4:0E:00:7E:BE"}]}

fritz.box associatedDevice[00:80:92:CD:F8:8B,authState] 1

fritz.box associatedDevice[00:80:92:CD:F8:8B,signalStrength] 79

fritz.box associatedDevice[00:80:92:CD:F8:8B,speed] 1

fritz.box associatedDevice[00:80:92:CD:F8:8B,ipAddress] 192.168.11.23

fritz.box associatedDevice[7E:C0:EE:63:1A:1C,authState] 1

fritz.box associatedDevice[7E:C0:EE:63:1A:1C,signalStrength] 81

fritz.box associatedDevice[7E:C0:EE:63:1A:1C,speed] 114

fritz.box associatedDevice[7E:C0:EE:63:1A:1C,ipAddress] 192.168.11.97

fritz.box associatedDevice[68:A4:0E:00:7E:BE,authState] 1

fritz.box associatedDevice[68:A4:0E:00:7E:BE,signalStrength] 89

fritz.box associatedDevice[68:A4:0E:00:7E:BE,speed] 39

fritz.box associatedDevice[68:A4:0E:00:7E:BE,ipAddress] 192.168.11.225

 

 

die accociated devices bei den entsprechenden IP adressen machen für mich keinen sinn..?! dier 23er ist ein drucker, der 97 gerade offline, und der 225er ein Ofen ….

 

 

 

 

Von: Patrick Thoelken ***@***.***> 
Gesendet: Mittwoch, 1. November 2023 12:15
An: pthoelken/fritzbox-zabbix-monitoring ***@***.***>
Cc: Rascree ***@***.***>; Mention ***@***.***>
Betreff: Re: [pthoelken/fritzbox-zabbix-monitoring] zabbix_sender [8]: ERROR: [line 8] 'Key value' required (Issue #10)

 

Danke für deine Rückmeldung. Gehe mal bitte in die CLI deines laufenden Containers und führe das folgende aus:

php status.php

und poste das Ergebnis. Sensible Daten wie IP Adresse bitte verfälschen / schwärzen.

**Comment by pthoelken** [comment]
Ist das bei dir aktiviert? 
![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/12643853/64130755-2eb7-4fe2-b3ca-adfab0ba8a31)

Sind die Einstellungen gesetzt? 
![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/12643853/7e1f5739-a23d-49c6-97c0-ea4f424771ea)

**Comment by Rascree** [comment]
Das Meiste. Heimnetz ist freigegeben. Zabbixmonitor hat alle rechte außer Zugang zum NAS und VPN, und keinen Zugang aus dem Internet. 

 



 

 

 

 

Von: Patrick Thoelken ***@***.***> 
Gesendet: Mittwoch, 1. November 2023 12:36
An: pthoelken/fritzbox-zabbix-monitoring ***@***.***>
Cc: Rascree ***@***.***>; Mention ***@***.***>
Betreff: Re: [pthoelken/fritzbox-zabbix-monitoring] zabbix_sender [8]: ERROR: [line 8] 'Key value' required (Issue #10)

 

Ist das bei dir aktiviert?
 <https://user-images.githubusercontent.com/12643853/279662163-64130755-2eb7-4fe2-b3ca-adfab0ba8a31.png> 

Sind die Einstellungen gesetzt?
 <https://user-images.githubusercontent.com/12643853/279662259-7e1f5739-a23d-49c6-97c0-ea4f424771ea.png>

**Comment by Rascree** [comment]
Ich sehe auch die anmeldungen des monitors in den Ereignissen. Komischer weise immer von anderen IPs. Das kann aber sein, dass der Monitor durch viele Restarts immer neue IPs zugewiesen bekommen hat. Aber es scheint hier zu funktionieren…

 



 

Von: Patrick Thoelken ***@***.***> 
Gesendet: Mittwoch, 1. November 2023 12:36
An: pthoelken/fritzbox-zabbix-monitoring ***@***.***>
Cc: Rascree ***@***.***>; Mention ***@***.***>
Betreff: Re: [pthoelken/fritzbox-zabbix-monitoring] zabbix_sender [8]: ERROR: [line 8] 'Key value' required (Issue #10)

 

Ist das bei dir aktiviert?
 <https://user-images.githubusercontent.com/12643853/279662163-64130755-2eb7-4fe2-b3ca-adfab0ba8a31.png> 

Sind die Einstellungen gesetzt?
 <https://user-images.githubusercontent.com/12643853/279662259-7e1f5739-a23d-49c6-97c0-ea4f424771ea.png>

**Comment by pthoelken** [comment]
Kannst du vielleicht hier in der Webseite antworten oder aber die vorherigen E-Mails bei einer Mail Antwort entfernen? Das macht das ganze hier sehr unübersichtlich. 

Also verstehe ich richtig, es sieht genau so aus, wie bei mir auf den Bildern?

**Comment by Rascree** [comment]
nicht 1:1, da ich für den zabbixmonitor den NAS und VPN nicht freigegeben habe. Ebenso Zugang aus dem Internet. Die Heimnetzfreigaben sind aber angehakt, d.h. Zugriff für Anwendungen und UPnP ist da.

**Comment by pthoelken** [comment]
Was für eine FritzBox hast du? Aktuell ergibt das für mich wenig sinn, dass einige Daten nicht sauber ankommen bei dir. 

Also, dass du den Fehler hast, liegt daran, dass einige Daten nicht sauber abgerufen werden können. Wenn da etwas fehlt, kommen "komische" Fehlermeldungen im Zabbix-Sender. Also der Zabbix-Sender läuft korrekt, es liegt eher daran, dass die Fritte nicht korrekt die Daten in den Soap Client gibt.

**Comment by Rascree** [comment]
Ich habe die Fritzbox 4040, 4060 und 7430. Ich habe es nacheinander über alle 3 boxen laufen lassen. Kontrolle über die Ereignismonitore, dass ich auch immer eine erfolgreiche Anmeldung hatte. Soweit passt das. Leider bekomme ich immernoch denselben Fehler bei allen Boxen. über "Key value"

**Comment by pthoelken** [comment]
Fungieren alle drei Fritzboxen als DSL Modem oder sind auch welche dabei, die nur als Switch / Access Point fungieren? Das würde erklären, wieso auf DSL (Layer1) teilweise keine Daten kommen, wenn dort nichts angeschlossen ist.

**Comment by Rascree** [comment]
Es funktioniert keine davon als DSL Modem. Die sind alle nur als AP unterwegs.

**Comment by pthoelken** [comment]
Okay, dann werde ich vermutlich wissen woran es liegt. Gebe mir ein paar Tage zeit den Fehler zu beheben. Bin gerade noch an etwas anderem dran und die Zeit ist ein wenig eng aktuell :-D

**Comment by pthoelken** [comment]
Teste es bitte nochmal. 

1. Pull latest Image (docker-compose down && docker-compose pull - oder Portainer)
2. Import latest Templates from https://github.com/pthoelken/fritzbox-zabbix-monitoring/tree/9-fr-fetch-the-layer1-down-and-upstream/templates (I've added some new values)
3. Added ENV Value` ZABBIX_SENDER_DEBUG=True `so your docker-compose.yml file (True if you want debug informations, false if you didn't want). 

Wenn du das alles gemacht hast, gehe nochmal in den Container und führe `php status.php` aus und paste das Ergebnis hier.

**Comment by Rascree** [comment]
all done

/app # php status.php
fritz.box totalBytesSent 0
fritz.box totalBytesReceived 0
fritz.box layer1UpstreamMaxBitRate 0
fritz.box layer1DownstreamMaxBitRate 0
fritz.box physicalLinkStatus Up
fritz.box ipAddressFromRouter 192.168.11.135
fritz.box connectionStatus Unconfigured
fritz.box uptime 0
fritz.box externalIPAddress not configured (check ipAddressFromRouter value)
fritz.box softwareVersion 155.07.57
fritz.box associatedDeviceDiscovery {"data":[]}

Container log:
Response from "192.168.11.177:10051": "processed: 0; failed: 11; total: 11; seconds spent: 0.000098"
sent: 11; skipped: 0; total: 11

**Comment by pthoelken** [comment]
Das sieht doch schon mal gut aus. 

Hast du `ZABBIX_SENDER_DEBUG=True` bei dir im docker-compose-File? Dann sollte man noch besser sehen, wieso es nicht gesendet wird.

Hast du das Template denn importiert?

**Comment by Rascree** [comment]
Ja, hatte ich alles gemacht. Ich hatte noch vergessen das Template im Host selbst nochmal neu einzuspielen. Jetzt kommt was im zabbix an.


connectionStatus | 17s | Unconfigured |   | Application: status | History |  
-- | -- | -- | -- | -- | -- | --
  | Fritz Box 4060 | externalIPAddress | 17s | not configured (check ipAddressFromRouter value) |   | Application: status | History |  
  | Fritz Box 4060 | ipAddressFromRouter | 17s | 192.168.11.135 |   |   | History |  
  | Fritz Box 4060 | layer1DownstreamCurrentUtilization |   |   |   | Application: status | Graph |  
  | Fritz Box 4060 | layer1DownstreamMaxBitRate | 17s | 0 Bit |   | Application: status | Graph |  
  | Fritz Box 4060 | layer1UpstreamCurrentUtilization |   |   |   | Application: status | Graph |  
  | Fritz Box 4060 | layer1UpstreamMaxBitRate | 17s | 0 Bit |   | Application: status | Graph |  
  | Fritz Box 4060 | physicalLinkStatus | 17s | Up |   | Application: status | History |  
  | Fritz Box 4060 | softwareVersion | 17s | 155.07.57 |   | Application: status | History |  
  | Fritz Box 4060 | totalBytesReceived | 17s | 0 Byte |   | Application: traffic | Graph |  
  | Fritz Box 4060 | totalBytesReceivedRate | 16s | 0 Byte/s |   | Application: traffic | Graph |  
  | Fritz Box 4060 | totalBytesSent | 17s | 0 Byte |   | Application: traffic | Graph |  
  | Fritz Box 4060 | totalBytesSentRate | 14s | 0 Byte/s |   | Application: traffic | Graph |  
  | Fritz Box 4060 | uptime | 17s | 0 |   | Application: status | Graph

**Comment by pthoelken** [comment]
Das ist doch schön. Es ist aktuell noch normal, dass keine Werte bei "layer1UpstreamMaxBitRate" angezeigt werden. Hiermit würde ich den aktuellen Case erst einmal schließen.

**Comment by Rascree** [comment]
prima. danke. ich nehme a für 3 boxen muss ich dann drei container bnutzen.

**Comment by pthoelken** [comment]
> prima. danke. ich nehme a für 3 boxen muss ich dann drei container bnutzen.

Ja, genau. 3 Container und 3 Hosts in Zabbix.
