### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by Jeepersfinest** [pthoelken/fritzbox-zabbix-monitoring#13]
Hi all,

i tried to install the docker image on my Qnap.
I found the Envs, but i don´t know "zabbix_sender_debug".

Could someone explain how to setup?

2ne Question: Which Interface i have to use in Zabbix on the host "fritzbox"? None?

Thanks a lot!
Christian

**Comment by pthoelken** [comment]
The host in zabbix should looks like this:

![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/12643853/11a4127f-0e2b-4d21-a7db-78308bd0e91e)

And the ENV `ZABBIX_SENDER_DEBUG=True` is giving you more informations while sending or not sending in the container cli. So if you didn't want to, feel free to disable it. :-)

**Comment by Jeepersfinest** [comment]
<img width="765" alt="Bildschirmfoto 2023-11-05 um 14 36 35" src="https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/42279947/da123a58-1471-4f38-af30-84769e5ceb6d">

Hi, thanks a lot for quick response!
I tried attached config, but Dpcker runs allways in 
`Pause for a time equal to the total of the args given, where each arg can
have an optional suffix of (s)econds, (m)inutes, (h)ours, or (d)ays
zabbix_sender [852]: invalid parameter "192.168.99.1"
zabbix_sender [852]: invalid parameter "60"
zabbix_sender [852]: invalid parameter "UserX"
zabbix_sender [852]: invalid parameter "PassX"
zabbix_sender [852]: invalid parameter "true"
`
Where is my fault?

**Comment by pthoelken** [comment]
Glad to help you :) If you have any questions, don't hesitate to contact me again.
