### ISSUE TITLE
FR: Customize Zabbix Server Port and Encryption

### ISSUE THREAD

**Issue by Pitastic** [pthoelken/fritzbox-zabbix-monitoring#14]
Hi !

My Zabbix Server instance is not running on the default port. It would be nice to customize this as an `ENV` in the `docker-compose.yaml`.

In `docker-compose.yaml` just add:

```diff
    environment:
      - ZABBIX_SERVER=00.00.00.00
+     - ZABBIX_SERVER_PORT=0000
```
and in `container/bin/send` :
```diff
	if [ "$ZABBIX_SENDER_DEBUG" == "True" ]; then
-		php status.php | zabbix_sender -vv -z $ZABBIX_SERVER -i -
+		php status.php | zabbix_sender -vv -z $ZABBIX_SERVER -p $ZABBIX_SERVER_PORT -i -
	else
-		php status.php | zabbix_sender -z $ZABBIX_SERVER -i -
+		php status.php | zabbix_sender -z $ZABBIX_SERVER -p $ZABBIX_SERVER_PORT -i -
	fi
```

Works perfectly for me !

**Comment by pthoelken** [comment]
Good point @Pitastic - let me check this in the next days. I've put it to my todo list. :-)

**Comment by Pitastic** [comment]
If we're talking about more settings ...it would also be nice to add (at least) TLS PSK encryption. Seems like bad practice to send such information unencrypted over the Internet (when Zabbix is not on the same network like in my case).

Therefore slightly more changes are necessary. I would like to implement both changes in a PR, what do you think?

**Comment by pthoelken** [comment]
I'll take a look into these as well

**Comment by Pitastic** [comment]
Hi,

ich hatte die Änderungen schon im Kopf und lokal ausprobiert. Bis zum Pull Request war es dann nicht mehr weit (ich hoffe, du hast dich damit noch nicht beschäftigt).

PR: #15
