### ISSUE TITLE
Sending fails with error

### ISSUE THREAD

**Issue by AdmiraalA** [pthoelken/fritzbox-zabbix-monitoring#17]
using podman version: 4.9.4-rhel
podman logs fritzbox-zabbix-monitoring_monitor_1
Using custom Zabbix Server port '10051'
Enable verbose logging
Using the following send command: zabbix_sender -z ******* -i - -p 10051 -vv
zabbix_sender [3]: ERROR: [line 1] 'Hostname' required

However, Hostname is set in the docker-compose file and matches the host in Zabbix

**Comment by pthoelken** [comment]
Thanks for your report. This issue is under investigation. Can you provide me a screenshot from your zabbix fritzbox host configuration window and paste your docker-compose.yml (without sensitive data) in here? 

Thanks.

**Comment by pthoelken** [comment]
I'll handling this behavior in #18. Thanks for your understanding.

**Comment by pthoelken** [comment]
Please try this image: pthoelken/fritzbox-zabbix-monitoring:dev-18

**Comment by AdmiraalA** [comment]
I'll try that image first before posting screenshots. In that case you'll have additional info

**Comment by AdmiraalA** [comment]
Not working either , the requested screenshot : 
![image](https://github.com/user-attachments/assets/ec64ba07-c97f-4941-8991-e1e589aa0c7f)

Config of the container : 

version: '3.2'
services:
  monitor:
    image: pthoelken/fritzbox-zabbix-monitoring:dev-18
    restart: always
    environment:
      - ZABBIX_SERVER=192.168.2.179
      - ZABBIX_SERVER_PORT=10051
      - TLS_PSK_IDENTITY=
      - TLS_PSK=
      - INTERVAL=30s
      - FRITZBOX_HOSTNAME=Fritzbox
      - FRITZBOX_IP=192.168.2.1
      - FRITZBOX_USER=*****
      - FRITZBOX_PASSWD=****
      - ZABBIX_SENDER_DEBUG=False

Server is 7.0.2 ( LTS) on RH 9

**Comment by pthoelken** [comment]
Okay, thanks for sharing this update to me. Honestly I have no running RHEL server here (so I have to create one in the next days). Give me some time to try to reproduce this. 

Did you try with the dev-18 to put the Hostname into quotes at the docker-compose.yml file? 

Which Zabbix server version did you use? 

Is there a difference if you change the hostname into another for the zabbix host item and in the docker-compose file?

**Comment by AdmiraalA** [comment]
Server is 7.0.2 , RHEL 9

Tried both your suggestions ( different image) and using quotes ( and tried changing host in zabbix) and without

**Comment by pthoelken** [comment]
Okay, so then give me some time to check this issue on RHEL systems. Thanks for your assistance.

**Comment by AdmiraalA** [comment]
No problem!
It's a good project tbh

**Comment by pthoelken** [comment]
@AdmiraalA Thanks for your compliment. Can you paste your output from this command `docker exec -it fritzmon_fritzbox-zabbix-monitoring_1 printenv` here (maybe you have to change the container name)? Remove sensitive data like passwords before pasting. Thanks.

**Comment by pthoelken** [comment]
When the container is up (errors doesn't matter) what is the output from this command here (again hide senstive data). 

`docker exec fritzmon_fritzbox-zabbix-monitoring_1 php status.php`

**Comment by AdmiraalA** [comment]
podman ps
CONTAINER ID  IMAGE                                                  COMMAND           CREATED      STATUS      PORTS       NAMES
9ee1ac94ea43  docker.io/pthoelken/fritzbox-zabbix-monitoring:dev-18  ash -c /app/send  3 hours ago  Up 3 hours              fritzbox-zabbix-monitoring_monitor_1
[root@okd4-snc-host fritzbox-zabbix-monitoring]# podman exec fritzbox-zabbix-monitoring_monitor_1 php status.php

Fatal error: Uncaught SoapFault exception: [s:Client] UPnPError in /app/status.php:18
Stack trace:
#0 /app/status.php(18): SoapClient->__call('GetAddonInfos', Array)
#1 {main}
  thrown in /app/status.php on line 18

**Comment by pthoelken** [comment]
Which model of FritzBox is in use and do you use it for a normal internet router like the isp is recommending this or you are using this as switch or wlan bridge only?

**Comment by AdmiraalA** [comment]
It's the 7590 and we use it as normal modem/router

**Comment by AdmiraalA** [comment]
I forgot the docker exec ..

docker exec -it fritzbox-zabbix-monitoring_monitor_1 printenv
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
container=podman
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHP_ASC_URL=https://www.php.net/distributions/php-8.2.20.tar.xz.asc
PHP_LDFLAGS=-Wl,-O1 -pie
GPG_KEYS=39B641343D8C104B2B146DC3F9C39DC0B9698544 E60913E4DF209907D8E30D96659A97C9CF2A795A 1198C0117593497A5EC5C199286AF1F9897469DC
INTERVAL=30s
PHP_SHA256=4474cc430febef6de7be958f2c37253e5524d5c5331a7e1765cd2d2234881e50
PHPIZE_DEPS=autoconf            dpkg-dev dpkg           file            g++             gcc             libc-dev                make            pkgconf                 re2c
PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
PHP_VERSION=8.2.20
PHP_URL=https://www.php.net/distributions/php-8.2.20.tar.xz
ZABBIX_SERVER_PORT=10051
TLS_PSK_IDENTITY=
FRITZBOX_USER=*****
ZABBIX_SENDER_DEBUG=False
ZABBIX_SERVER=192.168.2.179
PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
PHP_INI_DIR=/usr/local/etc/php
FRITZBOX_HOSTNAME="Fritzbox1"
FRITZBOX_IP=1.2.3.4
FRITZBOX_PASSWD=******
TLS_PSK=

**Comment by pthoelken** [comment]
Thanks, give me some time to investigate your model in case of this issue. It's seems to be, there is an incompability like from #18

**Comment by pthoelken** [comment]
Hey @AdmiraalA - checkout this comment from the similar issue here https://github.com/pthoelken/fritzbox-zabbix-monitoring/issues/18#issuecomment-2291053169 maybe this help to solve your problem.

**Comment by AdmiraalA** [comment]
Tried the suggestions mentioned there. Still same error

**Comment by DRReim** [comment]
@AdmiraalA, I did recreate the error with disabling UPNP, try and check if its enabled for you.

![image](https://github.com/user-attachments/assets/315f759a-19a1-475e-b6cc-fdf61c7ce5ba)

**Comment by AdmiraalA** [comment]
Upnp was enabled , but the Fritz didn't open the port somehow, after reboot i get stats.
