### ISSUE TITLE
Hostname Required, Sending failed

### ISSUE THREAD

**Issue by geiasounai** [pthoelken/fritzbox-zabbix-monitoring#18]
Hello,

Using the following send command: zabbix_sender -z <Zabbix_IP> -i - -p 10050 -vv
monitor_1  | zabbix_sender [8]: ERROR: [line 6] 'Hostname' required
monitor_1  | Sending failed.

Hostname correctly defined in docker_compose.yaml file, without " characters.

**Comment by pthoelken** [comment]
Thanks for your report. This issue is under investigation. Can you provide me a screenshot from your zabbix fritzbox host configuration window and paste your docker-compose.yml (without sensitive data) in here? 

Thanks.

**Comment by pthoelken** [comment]
Please try this image: pthoelken/fritzbox-zabbix-monitoring:dev-18

**Comment by geiasounai** [comment]
Hello!

![image](https://github.com/user-attachments/assets/64a66c0f-02fa-41bb-a467-245c5d986a26)

YAML file:

version: '3.2'
services:
  monitor:
    image: pthoelken/fritzbox-zabbix-monitoring:dev-18
    restart: always
    environment:
      - ZABBIX_SERVER=10.10.1.111
      - ZABBIX_SERVER_PORT=10050
      - INTERVAL=30s
      - FRITZBOX_HOSTNAME=ISP Router
      - FRITZBOX_IP=192.168.1.1
      - FRITZBOX_USER=****
      - FRITZBOX_PASSWD=*****
      - ZABBIX_SENDER_DEBUG=True

Tried with and without " characters at FRITZBOX_HOSTNAME field.

**Comment by pthoelken** [comment]
> Hello!
> 
> ![image](https://private-user-images.githubusercontent.com/46524450/356798362-64a66c0f-02fa-41bb-a467-245c5d986a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzg0MzQsIm5iZiI6MTcyMzI3ODEzNCwicGF0aCI6Ii80NjUyNDQ1MC8zNTY3OTgzNjItNjRhNjZjMGYtMDJmYS00MWJiLWE0NjctMjQ1YzVkOTg2YTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA4MjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlY2JiZWYzMTc4M2NkNGY4YjUzODQ5ZTdjMWMxM2Q3NzUwZTE3MDM3NzA1MzY3NjkxNzA1OGI0YjBhYjhlMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QRGJ2cJcqAy_XKtytflpYMp6Wc7sg3tMbAXHq4uSxpc)
> 
> YAML file:
> 
> version: '3.2' services: monitor: image: pthoelken/fritzbox-zabbix-monitoring:dev-18 restart: always environment: - ZABBIX_SERVER=10.10.1.111 - ZABBIX_SERVER_PORT=10050 - INTERVAL=30s - FRITZBOX_HOSTNAME=ISP Router - FRITZBOX_IP=192.168.1.1 - FRITZBOX_USER=**** - FRITZBOX_PASSWD=***** - ZABBIX_SENDER_DEBUG=True
> 
> Tried with and without " characters at FRITZBOX_HOSTNAME field.

Always it's a bad idea to use spaces in hostnames. Please remove the spaces in the hostname and try it again. 

Which base os did you use?

**Comment by pthoelken** [comment]
@geiasounai can you paste your output from this command `docker exec -it fritzmon_fritzbox-zabbix-monitoring_1 printenv` here (maybe you have to change the container name)? Remove sensitive data like passwords before pasting. Thanks.

**Comment by geiasounai** [comment]
@pthoelken , i tried without space in the hostname, with and without " characters but it still fails.
Please check below ouput from command requested:

root@fritzbox-zabbix-monitoring:~# docker exec -it root_monitor_1 printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=0f3f6bdeb943
TERM=xterm
ZABBIX_SERVER=10.10.1.111
ZABBIX_SERVER_PORT=10050
INTERVAL=30s
FRITZBOX_HOSTNAME=isprouter
FRITZBOX_IP=192.168.1.1
FRITZBOX_USER=****
FRITZBOX_PASSWD=****
ZABBIX_SENDER_DEBUG=True
PHPIZE_DEPS=autoconf            dpkg-dev dpkg           file            g++             gcc             libc-dev                make            pkgconf        re2c
PHP_INI_DIR=/usr/local/etc/php
PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
PHP_LDFLAGS=-Wl,-O1 -pie
GPG_KEYS=***************
PHP_VERSION=8.2.20
PHP_URL=https://www.php.net/distributions/php-8.2.20.tar.xz
PHP_ASC_URL=https://www.php.net/distributions/php-8.2.20.tar.xz.asc
PHP_SHA256=******************
HOME=/root


I run this in a docker container of Proxmox VE running an Ubuntu 22.04 template.

**Comment by pthoelken** [comment]
Did worked this anytime before for you or is this not working since day one?

**Comment by pthoelken** [comment]
When the container is up (errors doesn't matter) what is the output from this command here? 

`docker exec fritzmon_fritzbox-zabbix-monitoring_1 php status.php`

**Comment by pthoelken** [comment]
Did you use your FritzBox as normal internet router (as recommended from your isp) or for example as WiFi / switch extender only?

**Comment by pthoelken** [comment]
Which model? It seems to be that your Fritzbox does not support this item. Sorry for my bulk of questions but I only have the 7950 AX to test it.

`lanhostconfigmgm` and `"urn:dslforum-org:service:LANHostConfigManagement:1"`

**Comment by pthoelken** [comment]
Thanks, give me some time to investigate your model in case of this issue.

**Comment by DRReim** [comment]
Hello,

i got a similar issue. - Hostname required

Fritzbox 7590 - Zabbix server 7.0.2 running on debian 12
Dockerhost runnig on a proxmox LXC Container also debian 12
In zabbix my host the name is configured like the default -> fritz.box but I also tried out other names nothing helped

In the compose file I tried with " and without ", also tried the dev-18 too

/app # zabbix_sender -z 192.168.115.48 -i - -vv

zabbix_sender [39]: ERROR: [line 1] 'Hostname' required
Sending failed.

/app # printenv

ZABBIX_SENDER_DEBUG=False
HOSTNAME=0c9af3354d85
PHP_INI_DIR=/usr/local/etc/php
SHLVL=1
HOME=/root
TLS_PSK=
PHP_LDFLAGS=-Wl,-O1 -pie
FRITZBOX_IP=192.168.179.254
PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
FRITZBOX_PASSWD=******
PHP_VERSION=8.2.17
GPG_KEYS=*********
PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
PHP_ASC_URL=https://www.php.net/distributions/php-8.2.17.tar.xz.asc
PHP_URL=https://www.php.net/distributions/php-8.2.17.tar.xz
TERM=xterm
TLS_PSK_IDENTITY=
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
FRITZBOX_USER=Monitoring
INTERVAL=30s
PHPIZE_DEPS=autoconf            dpkg-dev dpkg           file            g++             gcc             libc-dev                make            pkgconf                 re2c
PWD=/app
PHP_SHA256=*******
ZABBIX_SERVER=192.168.115.48
FRITZBOX_HOSTNAME=fritz.box

/app # php status.php

fritz.box totalBytesSent 372423458
fritz.box totalBytesReceived 3082194351
fritz.box layer1UpstreamMaxBitRate 11859000
fritz.box layer1DownstreamMaxBitRate 48856000
fritz.box physicalLinkStatus Up
fritz.box ipAddressFromRouter 192.168.179.254
fritz.box connectionStatus Connected
fritz.box uptime 727061
fritz.box externalIPAddress ********
fritz.box softwareVersion 154.07.59
fritz.box associatedDeviceDiscovery {"data":[]}

**Comment by pthoelken** [comment]
This issue is under investigation. I need some time to find the troublemaker. If you wanna help me feel free to investigate this either :-)

**Comment by pthoelken** [comment]
@DRReim can you post the permissions from your fritzbox user? Thanks. The router in your network is running as normal isp router and direct internet access point?

**Comment by DRReim** [comment]
@pthoelken, sure I'm also trying to find out what's wrong, but my PHP skills aren't really good. This project is awesome, finally some good monitoring for AVM Routers.

Here are the permissions from my fritbox user.
![image](https://github.com/user-attachments/assets/1c82694a-aac9-4d06-9376-b4de5afbb0be)

Router is just setup as an internet router/modem, also doesn't do any firewalling, that's all handled by my opnsense. WLAN is disabled

FRITZ!OS is version 7.59

**Comment by pthoelken** [comment]
Just for testing, are you able set all permissions to the monitoring users (with vpn and so on) and test again. Thanks.

**Comment by pthoelken** [comment]
Really strange .. in my case; I have an new 7590 here and it works instant.

**Comment by DRReim** [comment]
> Just for testing, are you able set all permissions to the monitoring users (with vpn and so on) and test again. Thanks.

tried it with a User that has "full" rights. Did setup a fresh docker server + container just in case, but also doesn't seem to work.
in my firewall I allowed every port between the docker host, zabbix server and the fritzbox

just in case, here is the fritzbox host in zabbix

![image](https://github.com/user-attachments/assets/e2202b77-42aa-436c-9f79-b6adb8b05d19)

**Comment by DRReim** [comment]
Found the issue, was my fault.
Forgot to set the Listenport for Zabbix Trappers, changed the port in the docker-compose file to 10051 after restarting the zabbix server and it works.

![image](https://github.com/user-attachments/assets/f396a13f-85da-4dd9-81d1-4eee5fc124bd)

frizbox user has the recommended settings
open ports are now restricted to 49000 (docker server -> fritzbox)
and docker server -> zabbix host (10050 agent, 10051 agent trapper)

Thanks for the help and this awesome project! 👍

**Comment by pthoelken** [comment]
Perfect, thanks for your response and compliments. :-) just for my documentations, what was the error message from your docker container logs from the beginnging of the issue?

**Comment by DRReim** [comment]
My original error message were

**docker compose logs**
_fritzbox-zabbix-monitoring  | Using custom Zabbix Server port '10050'
fritzbox-zabbix-monitoring  | zabbix_sender [8]: ERROR: [line 1] 'Hostname' required
fritzbox-zabbix-monitoring  | Sending failed. Use option -vv for more detailed output._

after that I did
**docker exec fritzbox-zabbix-monitoring php status.php**

_Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in /app/status.php:18
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://192.168....', 'urn:schemas-upn...', 1, false)
#1 /app/status.php(18): SoapClient->__call('GetAddonInfos', Array)
#2 {main}
  thrown in /app/status.php on line 18_

allowed the docker server to access the fritzbox over port 49000 (in my firewall appliance) because different subnet
status.php Error message went away and it grapped the data

**docker compose logs**
_fritzbox-zabbix-monitoring  | Sending failed. Use option -vv for more detailed output._
fritzbox-zabbix-monitoring  | Sending failed. Use option -vv for more detailed output._
repeat_

did go into the container
**docker exec -it fritzbox-zabbix-monitoring sh
zabbix_sender -z <ZabbixServerIP> -i - -vv**

_zabbix_sender [26]: ERROR: [line 1] 'Hostname' required
Sending failed._

the error message really didn't help from the zabbix sender to solve this
hope this helps

**Comment by pthoelken** [comment]
Thanks for your response. I have to integrate some checks for a better error handling in the next image. 

@geiasounai check this message from here https://github.com/pthoelken/fritzbox-zabbix-monitoring/issues/18#issuecomment-2291053169 - maybe this solve your problem either.

**Comment by erik-van-dijk** [comment]
I'm getting the same error message ('Hostname' required), but seems to be another issue:
**docker exec fritzbox-zabbix-monitoring-monitor-1 php status.php**
fritz.box totalBytesSent 1718842744
fritz.box totalBytesReceived 3926947645
fritz.box layer1UpstreamMaxBitRate 999999000
fritz.box layer1DownstreamMaxBitRate 999999000
fritz.box physicalLinkStatus Up

Fatal error: Uncaught SoapFault exception: [HTTP] Unauthorized in /app/status.php:39
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://192.168....', 'urn:dslforum-or...', 1, false)
#1 /app/status.php(39): SoapClient->__call('GetInfo', Array)
#2 {main}
  thrown in /app/status.php on line 39

I'm connecting to a FRITZ!Box 7560 running FRITZ!OS: [07.30-108052 PLUS].
