### ISSUE TITLE
Error when importing template_avm_fritzbox.xml into Zabbix 6.0

### ISSUE THREAD

**Issue by ifgithub2016** [pthoelken/fritzbox-zabbix-monitoring#19]
Hello,
 
I know, the template was built for Zabbix 7.0 but maybe you have an idea why the import fails. I do get the following error message:

![grafik](https://github.com/user-attachments/assets/5e2d6bb8-2e89-41f2-8226-b7c3b23a5ce2)

Do you have an Idea what to adjust in which way to make the import running?

Thanks a lot

**Comment by ifgithub2016** [comment]
[Update]
I do get the same error message when trying to import the template_avm_fritzbox.xml into Zabbix 7.05...

**Comment by pthoelken** [comment]
Thanks for your report. I check this out the next days.

**Comment by ifgithub2016** [comment]
I tried to import the xml-File

**Comment by pthoelken** [comment]
So in version Zabbix 7.0.5 I can't reproduce the error. The template looks good. May you can try this template here, which is new exported from my dev station. 

[zbx_export_templates.zip](https://github.com/user-attachments/files/17606133/zbx_export_templates.zip)

**Comment by ifgithub2016** [comment]
Hello Patrick,

your fresh template i was able to import without any errors.

Thanks a lot for your support!
