### ISSUE TITLE
FR: Fetch the layer1 down and upstream

### ISSUE THREAD

**Issue by pthoelken** [pthoelken/fritzbox-zabbix-monitoring#9]
from @Lorgie1984

Is it possible to fetch the layer1 down and upstream?Actually there’s only totalBytesSendRate and receive which fetch’s the traffic also from the internal network. Internet traffic would be really nice. 😊

**Comment by pthoelken** [comment]
Now I have a little bit more time to investigate your request. Sorry for the late reply. 

As I understand you correctly @Lorgie1984 you mean the physical up and downstream rate from your internet provider, right? I fetch this already (usually on page 2 in latest data from your fritzbox host in zabbix.)

![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/12643853/5f49eb01-6356-428e-be20-aeac1ba092a5)

**Comment by Lorgie1984** [comment]
This is only the max bitrate from the DSL sync, I meant the traffic rate for layer1. Active down and upstream just for dsl, not the whole FRITZ!Box trafficVon meinem iPhone gesendetAm 27.10.2023 um 11:25 schrieb Patrick Thoelken ***@***.***>:﻿
Now I have a little bit more time to investigate your request. Sorry for the late reply.
As I understand you correctly @Lorgie1984 you mean the physical up and downstream rate from your internet provider, right? I fetch this already (usually on page 2 in latest data from your fritzbox host in zabbix.)

**Comment by pthoelken** [comment]
IMO this is the speed what you get from your ISP like Telekom, Vodafone, etc. If the isp internet connection (from your contract) is throttled the values will be updates. 

Or do you mean the real internet connection speed like a speedtest and these values put it into the zabbix fritzbox monitoring? I've do this in some versions ago on a local test stage but I've not implemented bc ... 

1. ... I have to meassure the real speed with a speed test which I do every, like 5 minutes. This will produce every 5 minutes a bunch of useless traffic into my network / fritzbox. 
2. ... the other thing is, when you are monitoring your whole network like me, every 5 minutes you got a peak into your network graphs. 

So, the "layer1DownstreamMaxBitRate" means the "configured" (by ISP) connection speed from ISP backbone to your fritzbox. The only way to determine the real-real speed is to implement a chronical speed test. 

Let me know if this helps a little. Otherwise I can show, how I implement a speedtest to this monitor in a modular function.

**Comment by Lorgie1984** [comment]
Ich antworte mal eben auf deutsch, da mein Englisch nicht so ausgeprägt ist :-D

Es wäre schön zu sehen, wieviel Traffic aktuell auf der DSL-Leitung verursacht wird.
Die Werte fritz.box: totalBytesSentRate & fritz.box: totalBytesReceivedRate zeigen augenscheinlich den gesamten Verkehr der Fritzbox an, auch im lokalen Netz, was ausschläge über 350Mbit/s enthält. 

Was mich interessiert, ist der Datendurchsatz der DSL-Leitung. Wieviel Up-/Download aktiv genutzt wird.

So dass ich im Verlauf z.B. sehen kann, ob nachts aktiver Traffic auf der Leitung von/nach aussen aktiv war.

Ich wüsste es jetzt nicht anders auszudrücken.

**Comment by pthoelken** [comment]
Ahhh, nun verstehe ich dich. Du meinst also die Usage / Nutzung der Layer1 Leitung (also die des DSL Kabels)? Gute Idee, jetzt wo ich drüber nachdenke interessiert es mich auch :D 

Ich schaue mal wie ich das umsetzen kann und melde mich dann wieder in den kommenden Tagen.

**Comment by pthoelken** [comment]
@Lorgie1984 - kannst du mir noch kurz sagen unter welche Zabbix Version nutzt du das ganze und kannst du die neuen Templates aus dem Templates Ordner auch importieren oder bekommst du da wie in #10 ebenfalls Probleme mit?

**Comment by Lorgie1984** [comment]
![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/6703382/341fd354-4941-48ec-9ee7-fee9387489e5)

Das template ließ sich problemlos importieren.

**Comment by pthoelken** [comment]
Hast du das alte Template vorher gelöscht?

**Comment by pthoelken** [comment]
Kurzes Update, ich habe dein Feature so gut wie umgesetzt. Muss gerade nur noch schauen, wie ich mit den Multilayer Values umgehe, welche ich bekomme, wenn ich DOCSIS Anschluss habe.

**Comment by pthoelken** [comment]
> ![image](https://user-images.githubusercontent.com/6703382/278992503-341fd354-4941-48ec-9ee7-fee9387489e5.png)
> 
> Gerade getestet: ![image](https://user-images.githubusercontent.com/6703382/279058763-863cdcf5-3c75-440a-8f63-95f35b6c467a.png)

Erst das alte Template löschen und dann das neue importieren. Wenn das alte Template noch vorhanden ist, kann es zu solchen Fehlern kommen.

**Comment by pthoelken** [comment]
@Lorgie1984 - magst du mir vielleicht einen gefallen tun? 

Magst du dir mal das Image mit dem Tag **:fr-09** ziehen und ganz normal mit deiner docker-compose.yml starten? Dann in den Container gehen und folgendes ausführen ....

`while true; do php dev.php | grep -i downstream; sleep 1; done`

... und anschließend ein wenig herunterladen? Am besten diese Testdatei hier http://ping.virtua.cloud/10GB.bin (kannst du anschließend wieder löschen). 

Bitte dann einmal das Ergebnis hier posten. 

Ich habe das Problem, dass ich ein Cable (DOCSIS) Anschluss habe und ich x-verschiedene Layer zurückbekomme in der Utilization. Ich möchte gerne wissen, ob das bei einem normalen DSL Anschluss ebenfalls der Fall ist. 

Danke für deine Mithilfe.

**Comment by Lorgie1984** [comment]
![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/6703382/f3aefcda-c4b8-46ba-9e8d-fa9badfee4f4)

Trotz löschen kommt der Fehler. Jetzt hab ich das alte Template nicht mehr da :-D

**Comment by pthoelken** [comment]
Sehr komisch, ich konnte das Template ohne Probleme importieren. https://github.com/pthoelken/fritzbox-zabbix-monitoring/blob/main/templates/template_avm_fritzbox.xml

Aber hier ist noch das alte: https://github.com/pthoelken/fritzbox-zabbix-monitoring/blob/382c1d8dce326b784f797a414c4e77f98f1bdd4d/templates/template_fritz.box.xml

![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/12643853/383c47c0-ff15-43a1-bcbd-0b5281f89538)

**Comment by pthoelken** [comment]
Aber das Template brauchst du für die Anfrage von mir https://github.com/pthoelken/fritzbox-zabbix-monitoring/issues/9#issuecomment-1793020500 auch nicht extra :-)

**Comment by Lorgie1984** [comment]
> @Lorgie1984 - magst du mir vielleicht einen Gefallen tun?
> 
> Magst du dir mal das Image mit dem Tag **:fr-09** ziehen und ganz normal mit deiner docker-compose.yml starten? Dann in den Container gehen und folgendes ausführen ....
> 
> `while true; do php dev.php | grep -i downstream; sleep 1; done`
> 
> ... und anschließend ein wenig herunterladen? Am besten diese Testdatei hier http://ping.virtua.cloud/10GB.bin (kannst du anschließend wieder löschen).
> 
> Bitte dann einmal das Ergebnis hier posten.
> 
> Ich habe das Problem, dass ich ein Cable (DOCSIS) Anschluss habe und ich x-verschiedene Layer zurückbekomme in der Utilization. Ich möchte gerne wissen, ob das bei einem normalen DSL Anschluss ebenfalls der Fall ist.
> 
> Danke für deine Mithilfe.

Ich lasse den Befehl im Linux Terminal laufen. Wo soll das Ergebnis erscheinen?
![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/6703382/df3b39bc-cd29-41d4-8fd7-f7673eadc738)

**Comment by Lorgie1984** [comment]
Der Container lässt keine bash zu und gibt einen Fehler aus:

![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/6703382/20f601db-42f5-44dd-99db-2ad35b5ab244)

**Comment by pthoelken** [comment]
> Der Container lässt keine bash zu und gibt einen Fehler aus:
> 
> ![image](https://user-images.githubusercontent.com/6703382/281525414-20f601db-42f5-44dd-99db-2ad35b5ab244.png)

`docker exec -it container_name /bin/bash`

**Comment by Lorgie1984** [comment]
![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/6703382/76603c09-eb7c-4715-b4ab-7c2a6e21efbe)


Kleiner Zusatz, bin jetzt im Container (bash mochte er nicht, aber sh), aber mir ist aufgefallen, das mit dem Container in Zabbix keine Werte zurückkommen und bei dem Befehl ausser dem Cursor nicht viel passiert.

![image](https://github.com/pthoelken/fritzbox-zabbix-monitoring/assets/6703382/5f3e4516-51d6-40d7-9321-f6e49f951c0b)

**Comment by Lorgie1984** [comment]
`pthoelken/fritzbox-zabbix-monitoring:fr-09`

Das Image zum Testen ist aber noch korrekt oder?

**Comment by pthoelken** [comment]
> `pthoelken/fritzbox-zabbix-monitoring:fr-09`
> 
> Das Image zum Testen ist aber noch korrekt oder?

Ja, genau, das ist korrekt.

**Comment by Lorgie1984** [comment]
`/app # while true; do php dev.php; sleep 1; done

Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in /app/dev.php:22
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://0192.168...', 'urn:dslforum-or...', 1, false)
#1 /app/dev.php(22): SoapClient->__call('GetCommonLinkPr...', Array)
#2 {main}
  thrown in /app/dev.php on line 22

Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in /app/dev.php:22
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://0192.168...', 'urn:dslforum-or...', 1, false)
#1 /app/dev.php(22): SoapClient->__call('GetCommonLinkPr...', Array)
#2 {main}
  thrown in /app/dev.php on line 22

Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in /app/dev.php:22
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://0192.168...', 'urn:dslforum-or...', 1, false)
#1 /app/dev.php(22): SoapClient->__call('GetCommonLinkPr...', Array)
#2 {main}
  thrown in /app/dev.php on line 22

Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in /app/dev.php:22
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://0192.168...', 'urn:dslforum-or...', 1, false)
#1 /app/dev.php(22): SoapClient->__call('GetCommonLinkPr...', Array)
#2 {main}
  thrown in /app/dev.php on line 22
`

**Comment by Lorgie1984** [comment]
```
sudo docker exec -it 5cb437cc50e6 /bin/ash
/app # while true; do php dev.php; sleep 1; done
fritz.box layer1DownstreamCurrentUtilization 2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239,3301778,3627524,3853992
fritz.box layer1DownstreamCurrentUtilization 887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513,1281776,94738,104956
fritz.box layer1DownstreamCurrentUtilization 2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239,3301778,3627524
fritz.box layer1DownstreamCurrentUtilization 1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513,1281776,94738
fritz.box layer1DownstreamCurrentUtilization 2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239,3301778,3627524
fritz.box layer1DownstreamCurrentUtilization 1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513,1281776,94738
fritz.box layer1DownstreamCurrentUtilization 2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239,3301778,3627524
fritz.box layer1DownstreamCurrentUtilization 1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513,1281776,94738
fritz.box layer1DownstreamCurrentUtilization 2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239,3301778,3627524
fritz.box layer1DownstreamCurrentUtilization 1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513,1281776,94738
fritz.box layer1DownstreamCurrentUtilization 2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239,3301778
fritz.box layer1DownstreamCurrentUtilization 1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513,1281776
fritz.box layer1DownstreamCurrentUtilization 2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239,3301778
fritz.box layer1DownstreamCurrentUtilization 1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513,1281776
fritz.box layer1DownstreamCurrentUtilization 2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239,3301778
fritz.box layer1DownstreamCurrentUtilization 1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513,1281776
fritz.box layer1DownstreamCurrentUtilization 2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239,3301778
fritz.box layer1DownstreamCurrentUtilization 1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513,1281776
fritz.box layer1DownstreamCurrentUtilization 2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239
fritz.box layer1DownstreamCurrentUtilization 757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513
fritz.box layer1DownstreamCurrentUtilization 2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239
fritz.box layer1DownstreamCurrentUtilization 757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513
fritz.box layer1DownstreamCurrentUtilization 2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265,3723239
fritz.box layer1DownstreamCurrentUtilization 757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496,102513
fritz.box layer1DownstreamCurrentUtilization 2843300,2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265
fritz.box layer1DownstreamCurrentUtilization 1095601,757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496
fritz.box layer1DownstreamCurrentUtilization 2843300,2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265
fritz.box layer1DownstreamCurrentUtilization 1095601,757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496
fritz.box layer1DownstreamCurrentUtilization 2843300,2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265
fritz.box layer1DownstreamCurrentUtilization 1095601,757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496
fritz.box layer1DownstreamCurrentUtilization 2843300,2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563,3366265
fritz.box layer1DownstreamCurrentUtilization 1095601,757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972,1798496
fritz.box layer1DownstreamCurrentUtilization 3542749,2843300,2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563
fritz.box layer1DownstreamCurrentUtilization 1215671,1095601,757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972
fritz.box layer1DownstreamCurrentUtilization 3542749,2843300,2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563
fritz.box layer1DownstreamCurrentUtilization 1215671,1095601,757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972
fritz.box layer1DownstreamCurrentUtilization 3542749,2843300,2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563
fritz.box layer1DownstreamCurrentUtilization 1215671,1095601,757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972
fritz.box layer1DownstreamCurrentUtilization 3542749,2843300,2942403,2743060,2661268,2905673,5951257,2840404,3260000,3595326,3319124,3044503,3376793,3195152,3820720,3632018,3440547,3433777,3271762,2947563
fritz.box layer1DownstreamCurrentUtilization 1215671,1095601,757948,1084941,1423978,887548,979286,871133,531039,1089393,883612,978331,980883,659116,399273,553437,1207689,1202603,4057199,3400972
```

**Comment by pthoelken** [comment]
Danke dir @Lorgie1984 - hast du DSL, Glasfaser oder Cable Anschluss?

**Comment by Lorgie1984** [comment]
VDSL 100

**Comment by pthoelken** [comment]
Aus zeitgründen kann ich das gerade leider nicht weiter verfolgen. Tut mir leid. Ist leider ein sehr zähes Stück Fleisch sauber an die Daten zu kommen.
